### ISSUE TITLE
subzy: command not found

### ISSUE THREAD

**Issue by Paradioss** [PentestPad/subzy#36]
can't run it and when installed manually asked : go: updates to go.mod needed; to update it:
        go mod tidy

**Comment by Paradioss** [comment]
please help

**Comment by Paradioss** [comment]
subzy: command not found

**Comment by lateralusd** [comment]
Hi, please provide step by step what did you do and what happened, also what is your operating system. Usually, it is enough just `go get github.com/LukaSikic/subzy@latest` and it should be inside your `$GOPATH`.
