### ISSUE TITLE
unable to run subzy with out absolute path

### ISSUE THREAD

**Issue by tehseensagar** [PentestPad/subzy#44]
I have just install subzy . I'm using go 1.18 version. my go apth env is set as well.  even I did export GOPATH=$HOME/go and
found that i have go/bin/subzy on path as well. But when I run subzy it does not find it. If I use /home/myuser/go/bin/subzy it is working fin. 

Any idea what went wrong?

**Comment by zin-htet-aung** [comment]
```cp /go/bin/subzy /usr/local/bin``` , it can solve

**Comment by ZishanAdThandar** [comment]
Solution: 
1. Use `export GOPATH=$HOME/go `  as root and normal user.
2. Then
    ```bash
    sudo cp $HOME/go/bin/* /usr/local/bin/*
    cp $HOME/go/bin/* /usr/local/bin/*
    ```
