### ISSUE TITLE
Subzy Showed Non Vuln Domain 

### ISSUE THREAD

**Issue by alpsrml** [PentestPad/subzy#48]
Hello.

I was try use the subzy but subzy showed all domain vuln as Akami
![2024-07-16 19_20_17-Window](https://github.com/user-attachments/assets/94885d62-6b90-4289-93a6-004fcfb013be)

**Comment by Hacker0neKD** [comment]
same as mine

**Comment by touhidshaikh** [comment]
I have fixed this issue in my repo and sent a PR (https://github.com/PentestPad/subzy/pull/51). 
If you need fast resolution you can use https://github.com/securityium/subzy repo.

**Comment by alpsrml** [comment]
@touhidshaikh i was installed ur version but nothing happen. I'm still false positive result.

**Comment by alpsrml** [comment]
Update: I was delete empty fingerprints on fingerprients.json file and the problem solve. Thx mate @touhidshaikh
