### ISSUE TITLE
Error: Process: Fingerprints

### ISSUE THREAD

**Issue by MedoX71T** [PentestPad/subzy#55]
$ subzy run --targets target.txt
`Error: Process: Fingerprints: invalid character ':' after top-level value`
$ go version
`go version go1.22.1 linux/amd64`
**Updated 3 times already ... its the same issue every time**

**Comment by MedoX71T** [comment]
i manually updated `fingerprint.json` file from `can-i-take-over-xyz` and it worked fine but literally every subdomain is **VULNERABLE**

**Comment by lydacious** [comment]
I have also created a issue regarding this. It shows every domain as vulnerable.

**Comment by edongkido** [comment]
Encountered the same issue as well

**Comment by 3RassRK** [comment]
Facing the same issue :(
```
root@98829:~/subdomains# subzy r --targets list.txt
Error: Process: Fingerprints: invalid character ':' after top-level value
```

**Comment by DrDisconnect27** [comment]
Same issue as well

**Comment by DevSuyashA** [comment]
same here, any solution that worked for y'all, even temporarily?

**Comment by acuciureanu** [comment]
@NSEcho I think you have to create a new release with a new version and that's by the guys are experiencing the problem.

Until then here's a workaround:

```sh
git clone https://github.com/PentestPad/subzy.git
cd subzy
go install .
```

**Comment by acuciureanu** [comment]
> Okay, I have pushed some changes, now by default with each run fingerprints will be checked with an upstream and if there are no fingerprints (it will download them), additionally, if there is a mismatch between two versions (local and upstream), it will download them again.
> 
> You can simply do `go install -v github.com/PentestPad/subzy@latest`.
> 
> Let me know if this fixed the issues you had.

i get

```
$ go install -v github.com/PentestPad/subzy@latest
go: github.com/PentestPad/subzy@latest: version constraints conflict:
        github.com/PentestPad/subzy@v1.1.0: parsing go.mod:
        module declares its path as: github.com/LukaSikic/subzy
                but was required as: github.com/PentestPad/subzy
```

**Comment by NSEcho** [comment]
Probably takes some time for Go proxy to update the changes, do `go install github.com/PentestPad/subzy@2a8493c`

**Comment by secfung** [comment]
I got the same error message "Error: Process: Fingerprints: invalid character ':' after top-level value" even ran "go install github.com/PentestPad/subzy@2a8493c". Thanks!

**Comment by NSEcho** [comment]
Can you check your home directory, there should be `subzy` directory and is there fingerprints.json inside of it?

**Comment by secfung** [comment]
Yes. I got this file.


┌──(root㉿kali)-[~/subzy]
└─# ls -al
total 12
drwxr-xr-x  2 root root 4096 Aug 27 15:26 .
drwx------ 46 root root 4096 Aug 27 15:26 ..
-rwxr-xr-x  1 root root   14 Aug 27 15:26 fingerprints.json

**Comment by secfung** [comment]
I deleted the fingerprints.json and re-run subzy but got the same error.

![Uploading Selection_014.png…]()

**Comment by NSEcho** [comment]
It appears to me that the issue is related to failed download of the fingerprints.json, is there anything that blocks your access to this github repo?

**Comment by NSEcho** [comment]
Meanwhile, as a workaround download this file https://raw.githubusercontent.com/EdOverflow/can-i-take-over-xyz/master/fingerprints.json and place it inside the `subzy` directory inside of your home directory.

**Comment by secfung** [comment]
It works without the error message now. Thanks a lot!

**Comment by lydacious** [comment]
> Probably takes some time for Go proxy to update the changes, do `go install github.com/PentestPad/subzy@2a8493c`

This worked. Thanks

**Comment by krn966** [comment]
> Okay, I have pushed some changes, now by default with each run fingerprints will be checked with an upstream and if there are no fingerprints (it will download them), additionally, if there is a mismatch between two versions (local and upstream), it will download them again.
> 
> You can simply do `go install -v github.com/PentestPad/subzy@latest`.
> 
> Let me know if this fixed the issues you had.

Worked for me. Thanks.
