### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by ndalezios** [PentestPad/subzy#57]
go: github.com/PentestPad/subzy@latest: version constraints conflict:
	github.com/PentestPad/subzy@v1.1.0: parsing go.mod:
	module declares its path as: github.com/LukaSikic/subzy
	        but was required as: github.com/PentestPad/subzy
Is it something that has to do with your go.mod?

I examined your src history and viewed your changes but maybe something needs rebuildor cashed out? 
Thanks

**Comment by NSEcho** [comment]
Please use `go install github.com/PentestPad/subzy@v1.2.0`.

**Comment by ndalezios** [comment]
Thanks man. Worked like a charm
